name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/api exec prisma format
      - run: pnpm -C apps/api exec prisma validate
      - run: pnpm run lint
      - run: pnpm run typecheck
      - run: pnpm -r run build
      - run: pnpm -r run test
